# Generated by Django 5.1.7 on 2025-03-10 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_newslettersubscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newslettersubscription',
            old_name='subscribded_at',
            new_name='subscribed_at',
        ),
    ]
