# Generated by Django 5.1.7 on 2025-03-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='website',
            field=models.TextField(default=''),
        ),
    ]
