# Generated by Django 5.1.7 on 2025-03-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_aboutprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('contacted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
