# Generated by Django 5.1.7 on 2025-03-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_comment_created_at_alter_contact_contacted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contacted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='subscribed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
