# Generated by Django 5.1.7 on 2025-03-16 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_leaders_alter_post_created_at_alter_post_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leaders',
            new_name='Leader',
        ),
    ]
