# Generated by Django 5.1.7 on 2025-03-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_leader_image_alter_leader_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='other_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
