# Generated by Django 5.1.7 on 2025-03-16 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_leader_other_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leader',
            name='other_name',
        ),
    ]
